# Generated by Django 3.1.7 on 2021-03-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('event_key', models.CharField(max_length=50)),
                ('category_id', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=150)),
                ('icon_sm', models.CharField(max_length=150)),
                ('icon_lg', models.CharField(max_length=150)),
                ('category_id', models.SmallIntegerField()),
                ('badge_type', models.SmallIntegerField(choices=[(1, 'Badges'), (2, 'Rewards'), (3, 'Levels'), (4, 'Points'), (5, 'Credits'), (6, 'Packages')], default=1)),
                ('icon_css', models.CharField(max_length=150)),
                ('priority', models.IntegerField(default=0)),
                ('credits', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('notification', models.CharField(max_length=300)),
                ('isdeduct', models.SmallIntegerField(default=0)),
                ('ilevel', models.SmallIntegerField(default=0)),
                ('ishide', models.SmallIntegerField(default=0)),
                ('ismultiple', models.SmallIntegerField(default=0)),
                ('img_url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BadgesCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('shorttitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category_type', models.SmallIntegerField(choices=[(1, 'Badges'), (2, 'Rewards'), (3, 'Levels'), (4, 'Points'), (5, 'Credits'), (6, 'Packages')], default=1)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BadgesUserAchievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('description', models.TextField()),
                ('createda_at', models.DateTimeField()),
                ('badge_type', models.SmallIntegerField(choices=[(1, 'Badges'), (2, 'Rewards'), (3, 'Levels'), (4, 'Points'), (5, 'Credits'), (6, 'Packages')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('badgeid', models.IntegerField()),
                ('badge_type', models.SmallIntegerField(choices=[(1, 'Badges'), (2, 'Rewards'), (3, 'Levels'), (4, 'Points'), (5, 'Credits'), (6, 'Packages')], default=1)),
                ('createda_at', models.DateTimeField()),
                ('repeated', models.SmallIntegerField()),
                ('badges', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamifyApp.badges')),
            ],
        ),
        migrations.AddField(
            model_name='badges',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamifyApp.badgescategories'),
        ),
    ]
